### ISSUE TITLE
Set --control_i to 10 or 11

### ISSUE THREAD

**Issue by hhuyujie** [AustinXY/GIRAFFEHD#1]
Thank you for releasing the code. Why do I get an error when I set -- CONTROL_i to 10 and 11?
`File "eval.py", line 120, in eval
    img_rep[args.control_i] = p
IndexError: list assignment index out of range`

**Comment by AustinXY** [comment]
Thanks for pointing that out. It seems like we forgot to include background rotation and translation into the image representation list (img_rep = [z_s_fg, z_a_fg, z_s_bg, z_a_bg, u, v, radius, s, t, rval]; which correspond to 0-9 of control_i). Background translation and rotation don't seem to be particularly interesting features to control, but if you would like to visualize those results, you can include bg_rval and bg_t to the image representation list and also modify [this function](https://github.com/AustinXY/GIRAFFEHD/blob/b331148e363c92cb1129a9dab76576a42c63d8c9/model.py#L394) to pass the bg_R and bg_t to the forward function.

**Comment by hhuyujie** [comment]
您好，我已收到您的邮件。

**Comment by AustinXY** [comment]
completed
