### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by SizheAn** [AustinXY/GIRAFFEHD#2]
Hi,

Nice work and congrats!

I'm trying to use your work as a baseline to my own dataset. However I find the training extremely slow.

Here's my training script:

python -m torch.distributed.launch --nproc_per_node=6 --master_port=$RANDOM train.py --wandb --batch 32 --dataset hairset --size 128 --datasize 128

With 6 V100, it is showing more than 900 hrs estimated time:

![image](https://user-images.githubusercontent.com/87412724/198348821-4809de79-7725-4c8c-95ea-125a413a155b.png)

Is it normal? What's your training strategy (epoch, batch size, etc.) for FFHQ-like dataset? Thank you.

**Comment by AustinXY** [comment]
Hi, 

We set the number of iterations in this codebase and not the number of epochs which means increasing the batch size and number of GPUs would make it run slower. You can set the number of iterations with --iter. I don't remember exactly but for FFHQ256 when I trained with a batch size of 8 and on 4 GPUs it took about 2 or 3 days to get to around 400k iterations. Usually, on a small dataset like FFHQ, the model gets pretty stable after about 300k iterations. 

Another observation was that batch size doesn't seem to have too much impact. If you would like to speed things up even more you can probably set the batch size to 16 or even 8.

**Comment by SizheAn** [comment]
> Hi,
> 
> We set the number of iterations in this codebase and not the number of epochs which means increasing the batch size and number of GPUs would make it run slower. You can set the number of iterations with --iter. I don't remember exactly but for FFHQ256 when I trained with a batch size of 8 and on 4 GPUs it took about 2 or 3 days to get to around 400k iterations. Usually, on a small dataset like FFHQ, the model gets pretty stable after about 300k iterations.
> 
> Another observation was that batch size doesn't seem to have too much impact. If you would like to speed things up even more you can probably set the batch size to 16 or even 8.

Thanks for the quick reply. Since I'm using batch of 32, I assume that my results in ~100k will be similar to batch size of 8 with ~400k iterations then.

Other questions: Do you reconstruct any 3D geometry/shape in GIRAFFEHD? Also, could you please share the code for computing MBS too?

**Comment by AustinXY** [comment]
You can use the [calc_mbs.py](https://github.com/AustinXY/GIRAFFEHD/blob/main/calc_mbs.py) to compute the MBS. 

Same as GIRAFFE, we only generate the 3D features at low resolution, so probably the only meaningful 3D geometry-relevant thing you can get is a low-resolution accumulation map.

**Comment by SizheAn** [comment]
> You can use the [calc_mbs.py](https://github.com/AustinXY/GIRAFFEHD/blob/main/calc_mbs.py) to compute the MBS.
> 
> Same as GIRAFFE, we only generate the 3D features at low resolution, so probably the only meaningful 3D geometry-relevant thing you can get is a low-resolution accumulation map.

Cool thanks! Btw, do you have the code for generating large number of fake images from a checkpoint? Thank you.

**Comment by SizheAn** [comment]
> You can use the [calc_mbs.py](https://github.com/AustinXY/GIRAFFEHD/blob/main/calc_mbs.py) to compute the MBS.
> 
> Same as GIRAFFE, we only generate the 3D features at low resolution, so probably the only meaningful 3D geometry-relevant thing you can get is a low-resolution accumulation map.
```
  File "calc_mbs.py", line 281, in <module>
    img1 = generator(img_rep, inject_index=2, mode='eval', _bg_img=bg0)[0]
  File "/home/tiger/anaconda3/envs/giraffehd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/tiger/anaconda3/envs/giraffehd/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/tiger/anaconda3/envs/giraffehd/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument '_bg_img'
```
Got this error for calc_mbs.py, any clue? Thanks.

**Comment by AustinXY** [comment]
I've updated the code and it should be good to go now. 

The problem was that previously I didn't buffer the noise for the background style generator, so I used a hacky way, stitch the foreground of the second image onto the background of the first image (when input the same noise and codes to the background branch it should always generate the same thing), to make sure that background stays constant. Now when you specify 'eval' mode, the style generators will load the buffered noises, so no hacky workaround is needed.

**Comment by SizheAn** [comment]
> I've updated the code and it should be good to go now.
> 
> The problem was that previously I didn't buffer the noise for the background style generator, so I used a hacky way, stitch the foreground of the second image onto the background of the first image (when input the same noise and codes to the background branch it should always generate the same thing), to make sure that background stays constant. Now when you specify 'eval' mode, the style generators will load the buffered noises, so no hacky workaround is needed.

Thank you. Sorry I have another question: If I want to change only the background instead of the foreground, how should I write the function? I mimic latent_change_bg but not sure if I did it correct since index can be tricky, could you please help check:

```
def latent_change_bg(generator, latents):
    # random sample z_s_bg, z_a_bg, transformations
    batch = latents[0].size(0)
    latents_ = generator.get_rand_rep(batch)
    # [z_s_bg, z_a_bg, s, t, rval]
    for i in [2,3,7,9]:
        latents[i] = latents_[i]
    # not sure what is 8 here?
    latents[8][:,0] = latents_[8][:,0]
    latents[8][:,1] = latents_[8][:,1]

    return latents
```

**Comment by AustinXY** [comment]
You can refer to the --control_i argument in eval.py for the feature each index controls. 

You probably don't want to change fg rotation, translation and scale (9, 8, 7), so it should probably be something like this:

```
def latent_change_bg(generator, latents):
    # random sample z_s_bg, z_a_bg, transformations
    batch = latents[0].size(0)
    latents_ = generator.get_rand_rep(batch)
    # [z_s_bg, z_a_bg, s, t, rval]
    for i in [2,3]:
        latents[i] = latents_[i]

    return latents
```

 latents[8] is a length 3 list corresponds to x, y, z translations. If you change z translation, the background will also change, hence we only randomize the x, y translations in latent_change_fg.

**Comment by SizheAn** [comment]
> You can refer to the --control_i argument in eval.py for the feature each index controls.
> 
> You probably don't want to change fg rotation, translation and scale (9, 8, 7), so it should probably be something like this:
> 
> ```
> def latent_change_bg(generator, latents):
>     # random sample z_s_bg, z_a_bg, transformations
>     batch = latents[0].size(0)
>     latents_ = generator.get_rand_rep(batch)
>     # [z_s_bg, z_a_bg, s, t, rval]
>     for i in [2,3]:
>         latents[i] = latents_[i]
> 
>     return latents
> ```
> 
> latents[8] is a length 3 list corresponds to x, y, z translations. If you change z translation, the background will also change, hence we only randomize the x, y translations in latent_change_fg.

Thank you it works.

If my dataset is 360 degree in terms of azim, should I set range_u to [0,1], or rotation_range?

**Comment by AustinXY** [comment]
You can set rotation_range to [0, 1] and range_u to [0, 0]. Basically range_u rotates both fg and bg, so if bg doesn't have huge variations at different angle, you can just factor everything into rotation_range.
