### ISSUE TITLE
MBS calculation 

### ISSUE THREAD

**Issue by LSH1231234** [AustinXY/GIRAFFEHD#3]
Hi!
Thank you for the awesome work and the code.

Where can I find  **TwoStageGenerator_Refine** class in **model.py**?
I was reading the codes in **calc_mbs.py**

**Comment by AustinXY** [comment]
Hi,

It's supposed to be just GIRAFFEHDGenerator, and I totally forgot to change it here. I have updated the code. Thanks for spotting it!
